//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssesmentUjjwal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AU_TL_UserDetails
    {
        [Display(Name = "Id")]
        public int aUserId { get; set; }

        [Required(ErrorMessage = "Company User Id is required")]
        public string vUserId { get; set; }

        [Required(ErrorMessage = "User Name is required")]
        public string vFullName { get; set; }

        [Required(ErrorMessage = "Mobile Number is required")]
        public string vMobile { get; set; }

        [Required(ErrorMessage = "Age is required")]
        public int iAge { get; set; }

        public long iSalary { get; set; }
    }
}
